kind: pipeline
name: RAD KERNEL BUILD #X86_64

clone:
  disable: true

steps:
- name: beta
  image: archlinux:latest
  environment:
      TG_BOT_API:
        from_secret: TG_BOT_API
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
  commands:
    - "export TG_BOT_API"
    - "export GITHUB_TOKEN"
    - pacman -Sy base-devel pahole github-cli bc llvm curl zip wget git --noconfirm
    - git clone --depth=1 --quiet https://github.com/theradcolor/linux -b ${DRONE_COMMIT_BRANCH} .
    - wget https://raw.githubusercontent.com/theradcolor/lazyscripts/master/ci-scripts/ci-x86
    - sed -i "s/TOKEN=.*/TOKEN=$TG_BOT_API/g" ci-x86
    - bash ci-x86
